// Auth
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const DEAUTHENTICATE = 'DEAUTHENTICATE';

export const ADD_RUN = 'ADD_RUN';
export const GET_RUNS = 'GET_RUNS';